# Generated by Django 5.1.7 on 2025-04-21 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0006_alter_userprofile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
