# Generated by Django 5.1.7 on 2025-04-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0010_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='guardian_email',
            field=models.CharField(blank=True, null=True),
        ),
    ]
