# Generated by Django 5.1.7 on 2025-03-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_room_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='availability',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Vacant', 'Vacant')], max_length=10, null=True),
        ),
    ]
