# Generated by Django 5.1.7 on 2025-04-07 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_chatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='full_name',
        ),
        migrations.AddField(
            model_name='tenant',
            name='first_name',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='last_name',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
