# Generated by Django 5.1.7 on 2025-04-07 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_remove_tenant_full_name_tenant_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='last_name',
        ),
        migrations.AddField(
            model_name='tenant',
            name='full_name',
            field=models.CharField(default='unknown', max_length=255),
        ),
    ]
