# Generated by Django 5.1.7 on 2025-04-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_remove_tenant_first_name_remove_tenant_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='full_name',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
