# Generated by Django 5.1.7 on 2025-04-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_tenant_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='full_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
