# Generated by Django 5.1.7 on 2025-04-19 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
