services:
  - type: web
    name: rms-web
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn rms.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: rms.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: rms-db
          property: connectionString

databases:
  - name: rms-db
    databaseName: rms_db
    user: rms_user
